# Day 01

In [1]:
import numpy as np

In [2]:
A = np.random.normal?

In [ ]:
A = np.random.normal

In [3]:
A = np.random.normal

In [4]:
A = np.random.normal(loc=1,scale=10,size=(10,3))
A

array([[ -7.19741113,  -6.80885316,  -3.26091549],
       [ -2.53157204, -10.16303444,  14.76935077],
       [  0.58541663,  11.23110481,  11.03708549],
       [ -2.91301366,   9.93857407,  11.32855664],
       [  3.13675552,   5.89250019,  -4.0391461 ],
       [ -8.14046874, -15.16346662,  -3.44444739],
       [ -0.54716098, -19.8065424 , -12.92462686],
       [ -2.10040752,  17.83412565,  10.22687787],
       [ -3.30095571,   6.59657355,   7.82470542],
       [  2.13210456,   7.00350812, -10.33119897]])

In [5]:
type(A)

numpy.ndarray

In [6]:
A.mean()

0.2288006026058693

In [7]:
A_y_mean = A.mean?

In [ ]:
A_y_mean = A.mean

In [8]:
A_y_mean = A.mean

среднее по столбцам

In [9]:
A_y_mean = A.mean(axis=0)
A_y_mean

array([-2.08767131,  0.65544898,  2.11862414])

стандартное отклонение

In [10]:
A_y_std = A.std?

In [ ]:
A_y_std = A.std

In [11]:
A_y_std = A.std

In [12]:
A_y_std = A.std(axis=0)

In [13]:
A_y_std

array([ 3.4599996 , 11.99097967,  9.49636077])

In [14]:
A_new = (A-A_y_mean) / A_y_std

In [15]:
A_new

array([[-1.47680359, -0.6224931 , -0.56648434],
       [-0.12829502, -0.90221848,  1.33216576],
       [ 0.77256886,  0.88196762,  0.93914517],
       [-0.23853828,  0.7741757 ,  0.9698381 ],
       [ 1.50995013,  0.43674924, -0.64843474],
       [-1.74936362, -1.31923463, -0.58581089],
       [ 0.44523425, -1.70644868, -1.58410694],
       [-0.00368099,  1.43263329,  0.85382748],
       [-0.35066027,  0.49546615,  0.60087032],
       [ 1.21958854,  0.52940288, -1.31100991]])

Выведите для заданной матрицы номера строк, сумма элементов в которых превосходит 1

In [16]:
a_sums = A_new.sum(axis=1)
a_sums

array([-2.66578103,  0.30165226,  2.59368165,  1.50547552,  1.29826462,
       -3.65440914, -2.84532137,  2.28277978,  0.7456762 ,  0.43798151])

In [17]:
np.nonzero(a_sums>0)

(array([1, 2, 3, 4, 7, 8, 9]),)

Сгенерируйте две единичные матрицы (т.е. с единицами на диагонали) размера 3x3. Соедините две матрицы в одну размера 6x3.

In [18]:
A = np.ones(shape=(3,3))
B = np.ones(shape=(3,3))

In [19]:
AB = np.vstack((A,B))

In [20]:
AB

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Day 2

In [21]:
import pandas as pd
from numpy import random
from matplotlib import pyplot as plt

In [22]:
# Enable inline plotting
%matplotlib inline

In [23]:
import sys #to determine python version
import matplotlib #to determine matplotlib version

In [24]:
sys.version

'3.7.6 (default, Jan  8 2020, 13:42:34) \n[Clang 4.0.1 (tags/RELEASE_401/final)]'

In [25]:
matplotlib.__version__

'3.1.3'

In [26]:
names = ['Bob', 'Alon', 'Max', 'Anna', 'Steve']

In [27]:
random.seed?

In [28]:
random.randint?

In [29]:
zip?

In [30]:
map?

In [31]:
random.seed(500)

In [32]:
random_int_from_length_of_names = random.randint(0, len(names))

In [33]:
names = [ names[random.randint(0, len(names))] for i in range(1000)]

In [34]:
names[:10]

['Alon', 'Alon', 'Bob', 'Alon', 'Alon', 'Alon', 'Max', 'Max', 'Max', 'Anna']

In [35]:
random.randint(low=0, high=1001)

155

In [36]:
births = [random.randint(low=0, high=1001) for i in range(1000)]

In [37]:
births[:10]

[77, 578, 973, 124, 155, 403, 199, 191, 769, 88]

In [38]:
BabyDataSet = list(zip(names,births))

In [39]:
BabyDataSet[:5]

[('Alon', 77), ('Alon', 578), ('Bob', 973), ('Alon', 124), ('Alon', 155)]

In [40]:
df = pd.DataFrame(BabyDataSet, columns=['Name','Birth'])

In [41]:
df

Name  Birth
0    Alon     77
1    Alon    578
2     Bob    973
3    Alon    124
4    Alon    155
..    ...    ...
995  Alon    756
996  Anna    294
997  Alon    152
998  Anna    905
999   Bob     52

[1000 rows x 2 columns]

In [42]:
df.to_csv('input/BabyDataSet.txt', index=False, header=False)

In [43]:
df = pd.read_csv('input/BabyDataSet.txt',header=None,names=['Name','Birth'])

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    1000 non-null   object
 1   Birth   1000 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 15.8+ KB


In [45]:
df.head()

Name  Birth
0  Alon     77
1  Alon    578
2   Bob    973
3  Alon    124
4  Alon    155

In [46]:
df['Name'].describe()

count     1000
unique       5
top        Bob
freq       207
Name: Name, dtype: object

In [47]:
df['Birth'].describe()

count    1000.000000
mean      496.939000
std       285.395266
min         1.000000
25%       253.500000
50%       494.000000
75%       729.000000
max       998.000000
Name: Birth, dtype: float64

In [48]:
dfGroupedByName = df.groupby('Name')

In [49]:
dfGroupedByName.mean()

Birth
Name             
Alon   501.515152
Anna   494.788660
Bob    491.362319
Max    503.076142
Steve  494.274510

In [50]:
plot = pd.DataFrame.plot(dfGroupedByName)

In [51]:
#plot.bar()

# Day 3

In [52]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy.random as np
import sys

In [53]:
%matplotlib inline

In [54]:
np.seed(111)

In [55]:
# Function to generate test data
def createDataSet(Number = 1):
    
    Output = []
    
    for i in range(Number):
        
        # Create a weekly (mondays) date range
        rng = pd.date_range(start='1/1/2009', end='12/31/2020', freq='W-MON')
        
        # Create random data
        data = np.randint(low=25, high=1000, size=len(rng))
        
        # Status pool
        status = [1,2,3]
        
        # Make a random list of statuses
        random_status = [status[np.randint(low=0,high=len(status))] for i in range(len(rng))]
        
        # State pool
        states = ['GA','FL','fl','NY','NJ','TX']
        
        # Make a random list of states 
        random_states = [states[np.randint(low=0,high=len(states))] for i in range(len(rng))]
    
        Output.extend(zip(random_states, random_status, data, rng))
        
    return Output

In [56]:
dataSet = createDataSet(10)

In [57]:
type(dataSet)

list

In [58]:
df = pd.DataFrame(data = dataSet, columns = ['state', 'status', 'CustomerCount', 'StatusDate'])

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6260 entries, 0 to 6259
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   state          6260 non-null   object        
 1   status         6260 non-null   int64         
 2   CustomerCount  6260 non-null   int64         
 3   StatusDate     6260 non-null   datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(1)
memory usage: 195.8+ KB


In [60]:
df.head()

state  status  CustomerCount StatusDate
0    FL       1            877 2009-01-05
1    TX       1            901 2009-01-12
2    TX       3            749 2009-01-19
3    fl       3            111 2009-01-26
4    NY       2            300 2009-02-02

In [61]:
df.to_excel("input/l3.xls", index=False)

In [62]:
df = pd.read_excel("input/l3.xls", sheet_name=0, index_col='StatusDate')

In [63]:
df

state  status  CustomerCount
StatusDate                             
2009-01-05    FL       1            877
2009-01-12    TX       1            901
2009-01-19    TX       3            749
2009-01-26    fl       3            111
2009-02-02    NY       2            300
...          ...     ...            ...
2020-11-30    TX       1            883
2020-12-07    FL       2            120
2020-12-14    NY       1            299
2020-12-21    GA       1            465
2020-12-28    FL       1            613

[6260 rows x 3 columns]

In [64]:
df.dtypes

state            object
status            int64
CustomerCount     int64
dtype: object

Preparing data

In [65]:
df.columns = ['State','Status','CustomerCount']

In [66]:
df.head()

State  Status  CustomerCount
StatusDate                             
2009-01-05    FL       1            877
2009-01-12    TX       1            901
2009-01-19    TX       3            749
2009-01-26    fl       3            111
2009-02-02    NY       2            300

In [67]:
df['State'].unique()

array(['FL', 'TX', 'fl', 'NY', 'GA', 'NJ'], dtype=object)

In [68]:
df.State.apply?

In [69]:
df['State'] = df.State.apply(lambda x : x.upper())

In [70]:
df['State'].unique()

array(['FL', 'TX', 'NY', 'GA', 'NJ'], dtype=object)

In [71]:
mask = df['Status'] == 1

In [72]:
df = df[mask]

In [73]:
df

State  Status  CustomerCount
StatusDate                             
2009-01-05    FL       1            877
2009-01-12    TX       1            901
2009-03-16    GA       1            978
2009-03-23    NY       1             32
2009-04-27    FL       1            753
...          ...     ...            ...
2020-11-16    FL       1            806
2020-11-30    TX       1            883
2020-12-14    NY       1            299
2020-12-21    GA       1            465
2020-12-28    FL       1            613

[2125 rows x 3 columns]

In [74]:
mask = df.State == 'NJ'
df['State'][mask] = 'NY'

/usr/local/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:8767: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)
